package com.acuity.rs.api;


//Generated by the injector on run.

//Abstract
//Extends com/acuity/rs/api/RSRenderable
public interface RSActor extends RSRenderable {

	int getActionFrame();

	int getAnimation();

	int getAnimationDelay();

	int getFineX();

	int getFineY();

	com.acuity.rs.api.RSNodeLinkedList getHealthBars();

	byte getHitsplatCount();

	int[] getHitsplatCycles();

	int[] getHitsplatIDs();

	int[] getHitsplats();

	int[] getHitsplatTypes();

	int getIdlePoseAnimation();

	int getOrientation();

	int getPathQueueSize();

	byte[] getPathQueueTraversed();

	int[] getPathXQueue();

	int[] getPathYQueue();

	int getPoseAnimation();

	int[] getSpecialHitsplats();

	int getSpotAnimation();

	int getSubAnimationFrame();

	int getTargetIndex();

	void invokeAddHitSplat(int var0, int var1, int var2, int var3, int var4, int var5);

	void setActionFrame(int var0);

	void setAnimation(int var0);

	void setAnimationDelay(int var0);

	void setFineX(int var0);

	void setFineY(int var0);

	void setHealthBars(com.acuity.rs.api.RSNodeLinkedList var0);

	void setHitsplatCount(byte var0);

	void setHitsplatCycles(int[] var0);

	void setHitsplatIDs(int[] var0);

	void setHitsplats(int[] var0);

	void setHitsplatTypes(int[] var0);

	void setIdlePoseAnimation(int var0);

	void setOrientation(int var0);

	void setPathQueueSize(int var0);

	void setPathQueueTraversed(byte[] var0);

	void setPathXQueue(int[] var0);

	void setPathYQueue(int[] var0);

	void setPoseAnimation(int var0);

	void setSpecialHitsplats(int[] var0);

	void setSpotAnimation(int var0);

	void setSubAnimationFrame(int var0);

	void setTargetIndex(int var0);
}
