package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSActor extends RSRenderable {

	int getActionAnimationDisable();

	int getActionFrame();

	int getAngle();

	int getAnimation();

	com.acuity.rs.api.RSNodeLinkedList getHealthBars();

	byte getHitsplatCount();

	int[] getHitsplatCycles();

	int[] getHitsplatIDs();

	int[] getHitsplats();

	int[] getHitsplatTypes();

	int getIdlePoseAnimation();

	int getOrientation();

	java.lang.String getOverhead();

	int[] getPathX();

	int[] getPathY();

	int getPoseAnimation();

	int getQueueSize();

	int[] getSpecialHitsplats();

	int getSpellAnimationID();

	int getStrictX();

	int getStrictY();

	int getSubAnimationFrame();

	int getTargetIndex();

	com.acuity.api.rs.wrappers.peers.scene.actors.Actor getWrapper();

	boolean isInSequence();

	void setActionAnimationDisable(int var0);

	void setActionFrame(int var0);

	void setAngle(int var0);

	void setAnimation(int var0);

	void setHealthBars(com.acuity.rs.api.RSNodeLinkedList var0);

	void setHitsplatCount(byte var0);

	void setHitsplatCycles(int[] var0);

	void setHitsplatIDs(int[] var0);

	void setHitsplats(int[] var0);

	void setHitsplatTypes(int[] var0);

	void setIdlePoseAnimation(int var0);

	void setInSequence(boolean var0);

	void setOrientation(int var0);

	void setOverhead(java.lang.String var0);

	void setPathX(int[] var0);

	void setPathY(int[] var0);

	void setPoseAnimation(int var0);

	void setQueueSize(int var0);

	void setSpecialHitsplats(int[] var0);

	void setSpellAnimationID(int var0);

	void setStrictX(int var0);

	void setStrictY(int var0);

	void setSubAnimationFrame(int var0);

	void setTargetIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.actors.Actor var0);
}
