package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.actors.Actor;
import java.lang.String;

//Generated by the injector on run.

//Extends: RSRenderable
public interface RSActor extends RSRenderable {

    int getActionAnimationDisable();

    int getActionFrame();

    int getAngle();

    int getAnimation();

    RSNodeLinkedList getHealthBars();

    int[] getHitsplatCycles();

    int getIdlePoseAnimation();

    int getOrientation();

    String getOverhead();

    int[] getPathX();

    int[] getPathY();

    int getPoseAnimation();

    int getQueueSize();

    int getSpellAnimationId();

    int getStrictX();

    int getStrictY();

    int getSubAnimationFrame();

    int getTargetIndex();

    Actor getWrapper();

    boolean isInSequence();
}
