package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSAnimationSequence extends RSCacheableNode {

	int getForcedPriority();

	int[] getFrameIDs();

	int[] getFrameLenghts();

	int getFrameStep();

	int[] getInterleaveLeave();

	int getLeftHandItem();

	int getMaxLoops();

	int getPrecedenceAnimating();

	int getPriority();

	int getReplyMode();

	int getRightHandItem();

	boolean isStretches();

	void setForcedPriority(int var0);

	void setFrameIDs(int[] var0);

	void setFrameLenghts(int[] var0);

	void setFrameStep(int var0);

	void setInterleaveLeave(int[] var0);

	void setLeftHandItem(int var0);

	void setMaxLoops(int var0);

	void setPrecedenceAnimating(int var0);

	void setPriority(int var0);

	void setReplyMode(int var0);

	void setRightHandItem(int var0);

	void setStretches(boolean var0);
}
