package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSArea extends RSCacheableNode {

	java.lang.String getName();

	int getSpriteId();

	void setName(java.lang.String var0);

	void setSpriteId(int var0);
}
