package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSAudioEffect {

	int getEnd();

	com.acuity.rs.api.RSAudioInstrument[] getInstruments();

	int getStart();

	void setEnd(int var0);

	void setInstruments(com.acuity.rs.api.RSAudioInstrument[] var0);

	void setStart(int var0);
}
