package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
//Implements java/lang/Runnable
public interface RSAudioRunnable extends java.lang.Runnable {

	com.acuity.rs.api.RSAudioSystem[] getSystems();

	void invokeRun();

	void setSystems(com.acuity.rs.api.RSAudioSystem[] var0);
}
