package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSAudioEnvelope {

	int getAmplitude();

	int getEnd();

	int getMax();

	int getPhaseIndex();

	int[] getPhases();

	int getStart();

	int getStep();

	int getTicks();

	void setAmplitude(int var0);

	void setEnd(int var0);

	void setMax(int var0);

	void setPhaseIndex(int var0);

	void setPhases(int[] var0);

	void setStart(int var0);

	void setStep(int var0);

	void setTicks(int var0);
}
