package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSAudioEffect {

    int getEnd();

    RSAudioInstrument[] getInstruments();

    int getStart();
}
