package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSAudioEnvelope {

    int getAmplitude();

    int getEnd();

    int getMax();

    int getPhaseIndex();

    int[] getPhases();

    int getStart();

    int getStep();

    int getTicks();
}
