package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSAudioSystem
public interface RSAudioSystemImpl extends RSAudioSystem {

	byte[] getBuffer();

	int getBufferSize();

	javax.sound.sampled.AudioFormat getFormat();

	javax.sound.sampled.SourceDataLine getSourceDataLine();

	void setBuffer(byte[] var0);

	void setBufferSize(int var0);

	void setFormat(javax.sound.sampled.AudioFormat var0);

	void setSourceDataLine(javax.sound.sampled.SourceDataLine var0);
}
