package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSBoundingBox
public interface RSAxisAlignedBoundingBox extends RSBoundingBox {

	int getColor();

	int getMaxX();

	int getMaxY();

	int getMaxZ();

	int getMinX();

	int getMinY();

	int getMinZ();

	void setColor(int var0);

	void setMaxX(int var0);

	void setMaxY(int var0);

	void setMaxZ(int var0);

	void setMinX(int var0);

	void setMinY(int var0);

	void setMinZ(int var0);
}
