package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSBufferProvider {

	int getHeight();

	int[] getPixels();

	int getWidth();

	void setHeight(int var0);

	void setPixels(int[] var0);

	void setWidth(int var0);
}
