package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSBuffer extends RSNode {

	int getOffset();

	byte[] getPayload();

	void setOffset(int var0);

	void setPayload(byte[] var0);
}
