package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSReferenceTable
public interface RSCacheReferenceTable extends RSReferenceTable {

	int getIndex();

	void setIndex(int var0);
}
