package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.peers.structures.CacheableNode;

//Generated by the injector on run.

//Extends: RSNode
public interface RSCacheableNode extends RSNode {

    RSCacheableNode getNext();

    RSCacheableNode getPrevious();

    CacheableNode getWrapper();
}
