package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSCacheableNode extends RSNode {

	com.acuity.rs.api.RSCacheableNode getNext();

	com.acuity.rs.api.RSCacheableNode getPrevious();

	com.acuity.api.rs.wrappers.peers.structures.CacheableNode getWrapper();

	void setNext(com.acuity.rs.api.RSCacheableNode var0);

	void setPrevious(com.acuity.rs.api.RSCacheableNode var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.structures.CacheableNode var0);
}
