package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSCameraCapture {

	int getComponentHeight();

	int getFlag();

	int getMaxStrictX();

	int getMaxStrictY();

	int getMinStrictX();

	int getMinStrictY();

	int getTileHeight();

	void setComponentHeight(int var0);

	void setFlag(int var0);

	void setMaxStrictX(int var0);

	void setMaxStrictY(int var0);

	void setMinStrictX(int var0);

	void setMinStrictY(int var0);

	void setTileHeight(int var0);
}
