package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSCameraCapture {

	int getComponentHeight();

	int getFlag();

	int getMaxFineX();

	int getMaxFineY();

	int getMinFineX();

	int getMinFineY();

	int getTileHeight();

	void setComponentHeight(int var0);

	void setFlag(int var0);

	void setMaxFineX(int var0);

	void setMaxFineY(int var0);

	void setMinFineX(int var0);

	void setMinFineY(int var0);

	void setTileHeight(int var0);
}
