package com.acuity.rs.api;

import java.awt.Component;

//Generated by the injector on run.

//Extends com/acuity/inject/classes/CanvasOverride
public interface RSCanvas {

    Component getTarget();
}
