package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.structures.CacheableNode;

//Generated by the injector on run.

//Extends RSNode
public interface RSCacheableNode {

    RSCacheableNode getNext();

    RSCacheableNode getPrevious();

    CacheableNode getWrapper();
}
