package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSChatLineBuffer {

	int getLength();

	com.acuity.rs.api.RSMessageNode[] getLines();

	void setLength(int var0);

	void setLines(com.acuity.rs.api.RSMessageNode[] var0);
}
