package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSChatMessages {

	java.lang.String[] getMessages();

	void setMessages(java.lang.String[] var0);
}
