package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSClassInfo extends RSNode {

	java.lang.reflect.Field[] getFields();

	byte[][][] getMethodArgs();

	java.lang.reflect.Method[] getMethods();

	void setFields(java.lang.reflect.Field[] var0);

	void setMethodArgs(byte[][][] var0);

	void setMethods(java.lang.reflect.Method[] var0);
}
