package com.acuity.rs.api;

import java.lang.reflect.Field;
import java.lang.reflect.Method;

//Generated by the injector on run.

//Extends RSNode
public interface RSClassInfo {

    Field[] getFields();

    byte[][][] getMethodArgs();

    Method[] getMethods();
}
