package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends: RSNode
public interface RSClanMember extends RSNode {

    String getName();

    byte getRank();

    String getUsername();

    int getWorld();
}
