package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSCollisionData {

	int[][] getFlags();

	int getHeight();

	int getInsetX();

	int getInsetY();

	int getWidth();

	void setFlags(int[][] var0);

	void setHeight(int var0);

	void setInsetX(int var0);

	void setInsetY(int var0);

	void setWidth(int var0);
}
