package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSCoordinates {

	int getPlane();

	int getWorldX();

	int getWorldY();

	void setPlane(int var0);

	void setWorldX(int var0);

	void setWorldY(int var0);
}
