package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSCollisionData {

    int[][] getFlags();

    int getHeight();

    int getInsetX();

    int getInsetY();

    int getWidth();
}
