package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSDevelopmentStage {

	int getId();

	java.lang.String getStage();

	void setId(int var0);

	void setStage(java.lang.String var0);
}
