package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSDevelopmentStage {

	int getID();

	java.lang.String getStage();

	void setID(int var0);

	void setStage(java.lang.String var0);
}
