package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSDefinitionProperty extends RSCacheableNode {

	int getDefaultInteger();

	java.lang.String getDefaultString();

	char getType();

	boolean isDeleteOnUse();

	void setDefaultInteger(int var0);

	void setDefaultString(java.lang.String var0);

	void setDeleteOnUse(boolean var0);

	void setType(char var0);
}
