package com.acuity.rs.api;


//Generated by the injector on run.

//Extends RSRenderable
public interface RSDynamicObject {

    int getId();

    int getLevel();

    int getOrientation();

    int getSceneX();

    int getSceneY();

    int getType();
}
