package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSDynamicObject extends RSRenderable {

	int getId();

	int getLevel();

	int getOrientation();

	int getSceneX();

	int getSceneY();

	int getType();

	int getY();

	void setId(int var0);

	void setLevel(int var0);

	void setOrientation(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setType(int var0);

	void setY(int var0);
}
