package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSEnum extends RSCacheableNode {

	int getDefaultInt();

	java.lang.String getDefaultString();

	int[] getIntVals();

	int[] getKeys();

	char getKeyType();

	int getSize();

	java.lang.String[] getStringVals();

	char getValType();

	void setDefaultInt(int var0);

	void setDefaultString(java.lang.String var0);

	void setIntVals(int[] var0);

	void setKeys(int[] var0);

	void setKeyType(char var0);

	void setSize(int var0);

	void setStringVals(java.lang.String[] var0);

	void setValType(char var0);
}
