package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSFileOnDisk {

	java.io.RandomAccessFile getFile();

	long getLength();

	long getPosition();

	void setFile(java.io.RandomAccessFile var0);

	void setLength(long var0);

	void setPosition(long var0);
}
