package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: RSNode
public interface RSFileSystem extends RSNode {

    byte[] getBuffer();

    RSIndexFile getIndex();

    RSIndexData getTable();
}
