package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSFileSystem extends RSNode {

	byte[] getBuffer();

	com.acuity.rs.api.RSIndexFile getIndex();

	com.acuity.rs.api.RSIndexData getTable();

	void setBuffer(byte[] var0);

	void setIndex(com.acuity.rs.api.RSIndexFile var0);

	void setTable(com.acuity.rs.api.RSIndexData var0);
}
