package com.acuity.rs.api;

import java.io.RandomAccessFile;

//Generated by the injector on run.

public interface RSFileOnDisk {

    RandomAccessFile getFile();

    long getLength();

    long getPosition();
}
