package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSFriendsListMember {

    String getName();

    String getPreviousName();

    int getRank();

    int getWorld();
}
