package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSFriendsListMember {

	java.lang.String getName();

	java.lang.String getPreviousName();

	int getRank();

	int getWorld();

	void setName(java.lang.String var0);

	void setPreviousName(java.lang.String var0);

	void setRank(int var0);

	void setWorld(int var0);
}
