package com.acuity.rs.api;


//Generated by the injector on run.

//Abstract
//Extends java/applet/Applet
//Implements java/lang/Runnable, java/awt/event/FocusListener, java/awt/event/WindowListener
public interface RSGameEngine extends java.lang.Runnable, java.awt.event.FocusListener, java.awt.event.WindowListener {

	java.awt.Canvas getCanvas();

	void setCanvas(java.awt.Canvas var0);
}
