package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGameEngine extends java.lang.Runnable, java.awt.event.FocusListener, java.awt.event.WindowListener {

	java.awt.Canvas getCanvas();

	com.acuity.api.rs.wrappers.peers.engine.GameEngine getWrapper();

	void setCanvas(java.awt.Canvas var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.engine.GameEngine var0);
}
