package com.acuity.rs.api;


//Generated by the injector on run.

//Extends RSRenderable
public interface RSGraphicsObject extends RSRenderable {

    int getHeight();

    int getId();

    int getLevel();

    int getSceneX();

    int getSceneY();
}
