package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGroundItemNode extends RSRenderable {

	int getID();

	int getStackSize();

	void setID(int var0);

	void setStackSize(int var0);
}
