package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGrandExchangeOffer {

    int getItemId();

    int getItemQuantity();

    int getPrice();

    int getQuantitySold();

    int getSpentMoney();

    byte getStatus();
}
