package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGraphicsObject extends RSRenderable {

	int getHeight();

	int getId();

	int getLevel();

	int getSceneX();

	int getSceneY();

	com.acuity.rs.api.RSAnimationSequence getSequence();

	void setHeight(int var0);

	void setId(int var0);

	void setLevel(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setSequence(com.acuity.rs.api.RSAnimationSequence var0);
}
