package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGrandExchangeOffer {

	int getItemId();

	int getItemQuantity();

	int getPrice();

	int getQuantitySold();

	int getSpentMoney();

	byte getStatus();

	void setItemId(int var0);

	void setItemQuantity(int var0);

	void setPrice(int var0);

	void setQuantitySold(int var0);

	void setSpentMoney(int var0);

	void setStatus(byte var0);
}
