package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSGrandExchangeOffer {

	int getItemID();

	int getItemQuantity();

	int getPrice();

	int getQuantitySold();

	int getSpentMoney();

	byte getStatus();

	void setItemID(int var0);

	void setItemQuantity(int var0);

	void setPrice(int var0);

	void setQuantitySold(int var0);

	void setSpentMoney(int var0);

	void setStatus(byte var0);
}
