package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSGroundItemNode extends RSRenderable {

	int getId();

	int getStackSize();

	void setId(int var0);

	void setStackSize(int var0);
}
