package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSHashTable {

	com.acuity.rs.api.RSNode[] getBuckets();

	com.acuity.rs.api.RSNode getHead();

	int getIndex();

	int getSize();

	com.acuity.rs.api.RSNode getTail();

	com.acuity.api.rs.wrappers.peers.structures.HashTable getWrapper();

	com.acuity.rs.api.RSNode invokeLookup(long var0);

	void setBuckets(com.acuity.rs.api.RSNode[] var0);

	void setHead(com.acuity.rs.api.RSNode var0);

	void setIndex(int var0);

	void setSize(int var0);

	void setTail(com.acuity.rs.api.RSNode var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.structures.HashTable var0);
}
