package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.structures.HashTable;

//Generated by the injector on run.

public interface RSHashTable {

    RSNode[] getBuckets();

    RSNode getHead();

    int getIndex();

    int getSize();

    RSNode getTail();

    HashTable getWrapper();
}
