package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSHealthBarComposite extends RSCacheableNode {

	int getHealthScale();

	com.acuity.api.rs.wrappers.peers.composite.HealthBarComposite getWrapper();

	void setHealthScale(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.HealthBarComposite var0);
}
