package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSHealthBar extends RSNode {

	com.acuity.rs.api.RSNodeLinkedList getHitsplats();

	com.acuity.rs.api.RSHealthBarType getType();

	void setHitsplats(com.acuity.rs.api.RSNodeLinkedList var0);

	void setType(com.acuity.rs.api.RSHealthBarType var0);
}
