package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSHealthBar extends RSNode {

	com.acuity.rs.api.RSNodeLinkedList getHitsplats();

	com.acuity.rs.api.RSHealthBarType getType();

	com.acuity.api.rs.wrappers.peers.scene.actors.accessories.HealthBar getWrapper();

	void setHitsplats(com.acuity.rs.api.RSNodeLinkedList var0);

	void setType(com.acuity.rs.api.RSHealthBarType var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.actors.accessories.HealthBar var0);
}
