package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSHealthBarComposite extends RSCacheableNode {

	com.acuity.api.rs.wrappers.peers.composite.HealthBarComposite getWrapper();

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.HealthBarComposite var0);
}
