package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSHealthBar extends RSNode {

	com.acuity.rs.api.RSHealthBarComposite getDefinition();

	com.acuity.rs.api.RSNodeLinkedList getHitsplats();

	void setDefinition(com.acuity.rs.api.RSHealthBarComposite var0);

	void setHitsplats(com.acuity.rs.api.RSNodeLinkedList var0);
}
