package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSHealthBarType extends RSCacheableNode {

	int getMaxWidth();

	int getOverlaySpriteId();

	int getUnderlaySpriteId();

	com.acuity.api.rs.wrappers.peers.types.HealthBarType getWrapper();

	void setMaxWidth(int var0);

	void setOverlaySpriteId(int var0);

	void setUnderlaySpriteId(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.types.HealthBarType var0);
}
