package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSHitBar extends RSNode {

	int getCycle();

	int getHealth();

	int getHealthRatio();

	void setCycle(int var0);

	void setHealth(int var0);

	void setHealthRatio(int var0);
}
