package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSHitUpdate extends RSNode {

	int getCurrentCycle();

	int getCurrentWidth();

	int getStartCycle();

	int getStartWidth();

	void setCurrentCycle(int var0);

	void setCurrentWidth(int var0);

	void setStartCycle(int var0);

	void setStartWidth(int var0);
}
