package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSHitsplatDefinition extends RSCacheableNode {

	java.lang.String getAmount();

	int getComparisonType();

	int getDuration();

	int getFade();

	int getFontID();

	int getIconID();

	int getLeftSpriteID();

	int getMiddleSpriteId();

	int getOffsetX();

	int getOffsetY();

	int getRightSpriteId();

	int getTextColor();

	int[] getTransformIDs();

	int getVarpbitIndex();

	int getVarpIndex();

	void setAmount(java.lang.String var0);

	void setComparisonType(int var0);

	void setDuration(int var0);

	void setFade(int var0);

	void setFontID(int var0);

	void setIconID(int var0);

	void setLeftSpriteID(int var0);

	void setMiddleSpriteId(int var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setRightSpriteId(int var0);

	void setTextColor(int var0);

	void setTransformIDs(int[] var0);

	void setVarpbitIndex(int var0);

	void setVarpIndex(int var0);
}
