package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSIdentikit {

	int getID();

	boolean isShowing();

	void setID(int var0);

	void setShowing(boolean var0);
}
