package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSIdentikit {

    int getId();

    int[] getTranslator_x();

    int[] getTranslator_y();

    int[] getTranslator_z();

    boolean isShowing();
}
