package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSIgnoreListMember {

	java.lang.String getName();

	java.lang.String getPreviousName();

	void setName(java.lang.String var0);

	void setPreviousName(java.lang.String var0);
}
