package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSIgnoreListMember {

    String getName();

    String getPreviousName();
}
