package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSInterfaceNode extends RSNode {

	int getId();

	int getState();

	void setId(int var0);

	void setState(int var0);
}
