package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSInterfaceComponent extends RSNode {

	java.lang.String[] getActions();

	int getBorderThickness();

	int getBoundsIndex();

	int getButtonType();

	int getComponentIndex();

	com.acuity.rs.api.RSInterfaceComponent[] getComponents();

	int getConfig();

	java.lang.Object[] getConfigListenerArgs();

	int[] getConfigTriggers();

	int getContentType();

	int[][] getDynamicValues();

	int getEnabledMaterialId();

	int getFondId();

	int getHeight();

	java.lang.Object[] getHoverListeners();

	int getInsetY();

	int getItemId();

	int[] getItemIds();

	int getItemStackSize();

	int[] getItemStackSizes();

	int getMaterialId();

	int getModelId();

	int getModelOffsetX();

	int getModelOffsetY();

	int getModelType();

	int getModelZoom();

	java.lang.Object[] getMouseEnterListeners();

	java.lang.Object[] getMouseExitListeners();

	java.lang.String getName();

	int getOpacity();

	int getOriginalWidth();

	int getOriginalX();

	int getOriginalY();

	com.acuity.rs.api.RSInterfaceComponent getParent();

	int getParentUid();

	int getRelativeX();

	int getRelativeY();

	int getRenderCycle();

	java.lang.Object[] getRenderListeners();

	int getRotationX();

	int getRotationY();

	int getRotationZ();

	int getScrollHeight();

	java.lang.Object[] getScrollListeners();

	int getScrollWidth();

	int getScrollX();

	java.lang.String getSelectedAction();

	int getShadowColor();

	java.lang.Object[] getSkillListenerArgs();

	int[] getSkillTriggers();

	int getSpriteId();

	int[] getTableActionInts();

	java.lang.String[] getTableActions();

	java.lang.Object[] getTableListenerArgs();

	int[] getTableTriggers();

	java.lang.String getText();

	int getTextColor();

	java.lang.String getTooltip();

	int getType();

	int getUid();

	int getWidth();

	com.acuity.api.rs.wrappers.peers.interfaces.InterfaceComponent getWrapper();

	int getXPadding();

	int getYPadding();

	boolean isFlippedHorizontally();

	boolean isFlippedVertically();

	boolean isHidden();

	boolean isScriptAvailable();

	boolean isTextShadowed();

	void setActions(java.lang.String[] var0);

	void setBorderThickness(int var0);

	void setBoundsIndex(int var0);

	void setButtonType(int var0);

	void setComponentIndex(int var0);

	void setComponents(com.acuity.rs.api.RSInterfaceComponent[] var0);

	void setConfig(int var0);

	void setConfigListenerArgs(java.lang.Object[] var0);

	void setConfigTriggers(int[] var0);

	void setContentType(int var0);

	void setDynamicValues(int[][] var0);

	void setEnabledMaterialId(int var0);

	void setFlippedHorizontally(boolean var0);

	void setFlippedVertically(boolean var0);

	void setFondId(int var0);

	void setHeight(int var0);

	void setHidden(boolean var0);

	void setHoverListeners(java.lang.Object[] var0);

	void setInsetY(int var0);

	void setItemId(int var0);

	void setItemIds(int[] var0);

	void setItemStackSize(int var0);

	void setItemStackSizes(int[] var0);

	void setMaterialId(int var0);

	void setModelId(int var0);

	void setModelOffsetX(int var0);

	void setModelOffsetY(int var0);

	void setModelType(int var0);

	void setModelZoom(int var0);

	void setMouseEnterListeners(java.lang.Object[] var0);

	void setMouseExitListeners(java.lang.Object[] var0);

	void setName(java.lang.String var0);

	void setOpacity(int var0);

	void setOriginalWidth(int var0);

	void setOriginalX(int var0);

	void setOriginalY(int var0);

	void setParent(com.acuity.rs.api.RSInterfaceComponent var0);

	void setParentUid(int var0);

	void setRelativeX(int var0);

	void setRelativeY(int var0);

	void setRenderCycle(int var0);

	void setRenderListeners(java.lang.Object[] var0);

	void setRotationX(int var0);

	void setRotationY(int var0);

	void setRotationZ(int var0);

	void setScriptAvailable(boolean var0);

	void setScrollHeight(int var0);

	void setScrollListeners(java.lang.Object[] var0);

	void setScrollWidth(int var0);

	void setScrollX(int var0);

	void setSelectedAction(java.lang.String var0);

	void setShadowColor(int var0);

	void setSkillListenerArgs(java.lang.Object[] var0);

	void setSkillTriggers(int[] var0);

	void setSpriteId(int var0);

	void setTableActionInts(int[] var0);

	void setTableActions(java.lang.String[] var0);

	void setTableListenerArgs(java.lang.Object[] var0);

	void setTableTriggers(int[] var0);

	void setText(java.lang.String var0);

	void setTextColor(int var0);

	void setTextShadowed(boolean var0);

	void setTooltip(java.lang.String var0);

	void setType(int var0);

	void setUid(int var0);

	void setWidth(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.interfaces.InterfaceComponent var0);

	void setXPadding(int var0);

	void setYPadding(int var0);
}
