package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSInterfaceNode extends RSNode {

	int getID();

	int getState();

	void setID(int var0);

	void setState(int var0);
}
