package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSISAACCipher {

    int[] getMm();

    int[] getRandResult();

    int getValuesRemaining();

    void invokeGenerateMoreResults();

    int invokeNextInt();
}
