package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSItemTable extends RSNode {

	int[] getItemIds();

	int[] getStackSizes();

	void setItemIds(int[] var0);

	void setStackSizes(int[] var0);
}
