package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSItemComposite extends RSCacheableNode {

	int getAmbient();

	int getContrast();

	int getFemaleHeadModel();

	int getFemaleHeadModel2();

	int getFemaleModel1();

	int getFemaleModel2();

	java.lang.String[] getGroundActions();

	int getID();

	java.lang.String[] getInventoryActions();

	int getMaleHeadModel();

	int getMaleHeadModel2();

	int getMaleModel1();

	int getMaleModel2();

	int getModelId();

	java.lang.String getName();

	int getNoteId();

	int getNoteTemplateId();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int getResizeX();

	int getResizeY();

	int getResizeZ();

	int getShiftClickActionIndex();

	int getSpritePitch();

	int getSpriteRoll();

	int getSpriteScale();

	int getSpriteTranslateX();

	int getSpriteTranslateY();

	int getSpriteYaw();

	int getTeam();

	int getValue();

	com.acuity.api.rs.wrappers.peers.composite.ItemComposite getWrapper();

	com.acuity.rs.api.RSModelComposite invokeGetEquipmentModel(boolean var0);

	com.acuity.rs.api.RSModel invokeGetModel(int var0);

	boolean isMembers();

	int isStackable();

	boolean isTradable();

	void setAmbient(int var0);

	void setContrast(int var0);

	void setFemaleHeadModel(int var0);

	void setFemaleHeadModel2(int var0);

	void setFemaleModel1(int var0);

	void setFemaleModel2(int var0);

	void setGroundActions(java.lang.String[] var0);

	void setID(int var0);

	void setInventoryActions(java.lang.String[] var0);

	void setIsStackable(int var0);

	void setMaleHeadModel(int var0);

	void setMaleHeadModel2(int var0);

	void setMaleModel1(int var0);

	void setMaleModel2(int var0);

	void setMembers(boolean var0);

	void setModelId(int var0);

	void setName(java.lang.String var0);

	void setNoteId(int var0);

	void setNoteTemplateId(int var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setResizeX(int var0);

	void setResizeY(int var0);

	void setResizeZ(int var0);

	void setShiftClickActionIndex(int var0);

	void setSpritePitch(int var0);

	void setSpriteRoll(int var0);

	void setSpriteScale(int var0);

	void setSpriteTranslateX(int var0);

	void setSpriteTranslateY(int var0);

	void setSpriteYaw(int var0);

	void setTeam(int var0);

	void setTradable(boolean var0);

	void setValue(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.ItemComposite var0);
}
