package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSItemLayer {

    RSRenderable getBottom();

    int getFlags();

    int getHash();

    int getHeight();

    RSRenderable getMiddle();

    RSRenderable getTop();

    int getX();

    int getY();
}
