package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSItemComposite extends RSCacheableNode {

	int getAmbient();

	int getContrast();

	int getFemaleHeadModel();

	int getFemaleHeadModel2();

	int getFemaleModel1();

	int getFemaleModel2();

	java.lang.String[] getGroundActions();

	int getID();

	java.lang.String[] getInventoryActions();

	int getInventoryModel();

	int getMaleHeadModel();

	int getMaleHeadModel2();

	int getMaleModel1();

	int getMaleModel2();

	java.lang.String getName();

	int getNoteTemplateId();

	int getOffsetX2d();

	int getOffsetY2d();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int getResizeX();

	int getResizeY();

	int getResizeZ();

	int getTeam();

	com.acuity.api.rs.wrappers.peers.composite.ItemComposite getWrapper();

	int getXan2d();

	int getYan2d();

	int getZan2d();

	int getZoom2d();

	com.acuity.rs.api.RSModelComposite invokeGetEquipmentModel(boolean var0);

	com.acuity.rs.api.RSModel invokeGetModel(int var0);

	boolean isMembers();

	int isStackable();

	void setAmbient(int var0);

	void setContrast(int var0);

	void setFemaleHeadModel(int var0);

	void setFemaleHeadModel2(int var0);

	void setFemaleModel1(int var0);

	void setFemaleModel2(int var0);

	void setGroundActions(java.lang.String[] var0);

	void setID(int var0);

	void setInventoryActions(java.lang.String[] var0);

	void setInventoryModel(int var0);

	void setIsStackable(int var0);

	void setMaleHeadModel(int var0);

	void setMaleHeadModel2(int var0);

	void setMaleModel1(int var0);

	void setMaleModel2(int var0);

	void setMembers(boolean var0);

	void setName(java.lang.String var0);

	void setNoteTemplateId(int var0);

	void setOffsetX2d(int var0);

	void setOffsetY2d(int var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setResizeX(int var0);

	void setResizeY(int var0);

	void setResizeZ(int var0);

	void setTeam(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.ItemComposite var0);

	void setXan2d(int var0);

	void setYan2d(int var0);

	void setZan2d(int var0);

	void setZoom2d(int var0);
}
