package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSItemLayer {

	com.acuity.rs.api.RSRenderable getBottom();

	int getFlags();

	int getHash();

	int getHeight();

	com.acuity.rs.api.RSRenderable getMiddle();

	com.acuity.rs.api.RSRenderable getTop();

	int getX();

	int getY();

	void setBottom(com.acuity.rs.api.RSRenderable var0);

	void setFlags(int var0);

	void setHash(int var0);

	void setHeight(int var0);

	void setMiddle(com.acuity.rs.api.RSRenderable var0);

	void setTop(com.acuity.rs.api.RSRenderable var0);

	void setX(int var0);

	void setY(int var0);
}
