package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSItemTable extends RSNode {

	int[] getItemIDs();

	int[] getStackSizes();

	void setItemIDs(int[] var0);

	void setStackSizes(int[] var0);
}
