package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSBoundingBox
public interface RSLegacy2DBoundingBox extends RSBoundingBox {

	int getColor();

	int getMaxX();

	int getMaxY();

	int getMinX();

	int getMinY();

	com.acuity.api.rs.wrappers.peers.rendering.bounding_boxes.Legacy2DBoundingBox getWrapper();

	void setColor(int var0);

	void setMaxX(int var0);

	void setMaxY(int var0);

	void setMinX(int var0);

	void setMinY(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.rendering.bounding_boxes.Legacy2DBoundingBox var0);
}
