package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSLegacy2DBoundingBox extends RSBoundingBox {

	int getColor();

	int getMaxX();

	int getMaxY();

	int getMinX();

	int getMinY();

	void setColor(int var0);

	void setMaxX(int var0);

	void setMaxY(int var0);

	void setMinX(int var0);

	void setMinY(int var0);
}
