package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSBufferProvider
public interface RSMainBufferProvider extends RSBufferProvider {

	java.awt.Image getImage();

	void invokeDraw(java.awt.Graphics var0, int var1, int var2);

	void invokeDrawSub(java.awt.Graphics var0, int var1, int var2, int var3, int var4);

	void setImage(java.awt.Image var0);
}
