package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSMainBufferProvider extends RSBufferProvider {

	java.awt.Image getImage();

	void setImage(java.awt.Image var0);
}
