package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSMainBufferProvider extends RSBufferProvider {

	java.awt.Image getImage();

	void invokeDraw(java.awt.Graphics var0, int var1, int var2, int var3);

	void invokeDrawSub(java.awt.Graphics var0, int var1, int var2, int var3, int var4, int var5);

	void setImage(java.awt.Image var0);
}
