package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSMessageNode extends RSCacheableNode {

	int getID();

	java.lang.String getName();

	java.lang.String getSender();

	int getTick();

	int getType();

	java.lang.String getValue();

	void setID(int var0);

	void setName(java.lang.String var0);

	void setSender(java.lang.String var0);

	void setTick(int var0);

	void setType(int var0);

	void setValue(java.lang.String var0);
}
