package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends RSCacheableNode
public interface RSMessageNode {

    int getId();

    String getName();

    String getSender();

    int getTick();

    int getType();

    String getValue();
}
