package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSModel extends RSRenderable {

	int[] getVerticesX();

	int[] getVerticesY();

	int[] getVerticesZ();

	int[] getXTriangles();

	int[] getYTriangles();

	int[] getZTriangles();

	void setVerticesX(int[] var0);

	void setVerticesY(int[] var0);

	void setVerticesZ(int[] var0);

	void setXTriangles(int[] var0);

	void setYTriangles(int[] var0);

	void setZTriangles(int[] var0);
}
