package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
//Implements java/lang/Runnable
public interface RSMouseRecorder extends java.lang.Runnable {

	int getIndex();

	java.lang.Object getLock();

	int[] getMouseXHistory();

	int[] getMouseYHistory();

	boolean isEnabled();

	void setEnabled(boolean var0);

	void setIndex(int var0);

	void setLock(java.lang.Object var0);

	void setMouseXHistory(int[] var0);

	void setMouseYHistory(int[] var0);
}
