package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: RSRasterizer2D
public interface RSModIcon extends RSRasterizer2D {

    int getHeight();

    int getOffsetX();

    int getOffsetY();

    int getOriginalHeight();

    int getOriginalWidth();

    int[] getPalette();

    byte[] getPixels();

    int getWidth();
}
