package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSModel extends RSRenderable {

	int[] getXTriangles();

	int[] getXVertices();

	int[] getYTriangles();

	int[] getYVertices();

	int[] getZTriangles();

	int[] getZVertices();

	void setXTriangles(int[] var0);

	void setXVertices(int[] var0);

	void setYTriangles(int[] var0);

	void setYVertices(int[] var0);

	void setZTriangles(int[] var0);

	void setZVertices(int[] var0);
}
