package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: RSRenderable
public interface RSModel extends RSRenderable {

    int[] getVerticesX();

    int[] getVerticesY();

    int[] getVerticesZ();

    int[] getXTriangles();

    int[] getYTriangles();

    int[] getZTriangles();
}
