package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSMouseRecorder extends java.lang.Runnable {

    int getIndex();

    boolean isEnabled();
}
