package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSMouseListener extends java.awt.event.MouseListener, java.awt.event.MouseMotionListener, java.awt.event.FocusListener {
}
