package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSModIcon extends RSRasterizer2D {

	int getHeight();

	int getOffsetX();

	int getOffsetY();

	int getOriginalHeight();

	int getOriginalWidth();

	int[] getPalette();

	byte[] getPixels();

	int getWidth();

	void setHeight(int var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setOriginalHeight(int var0);

	void setOriginalWidth(int var0);

	void setPalette(int[] var0);

	void setPixels(byte[] var0);

	void setWidth(int var0);
}
