package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNodeTable {

	com.acuity.rs.api.RSNodeQueue getQueue();

	com.acuity.rs.api.RSHashTable getTable();

	void setQueue(com.acuity.rs.api.RSNodeQueue var0);

	void setTable(com.acuity.rs.api.RSHashTable var0);
}
