package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNodeLinkedList extends java.lang.Iterable {

	com.acuity.rs.api.RSNode getNode();

	com.acuity.rs.api.RSNode getTail();

	com.acuity.api.rs.wrappers.peers.structures.NodeLinkedList getWrapper();

	void setNode(com.acuity.rs.api.RSNode var0);

	void setTail(com.acuity.rs.api.RSNode var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.structures.NodeLinkedList var0);
}
