package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.structures.NodeLinkedList;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSNodeLinkedList extends java.lang.Iterable {

    RSNode getNode();

    NodeLinkedList getWrapper();
}
