package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.structures.Node;

//Generated by the injector on run.

public interface RSNode {

    long getKey();

    RSNode getNext();

    RSNode getPrevious();

    Node getWrapper();

    boolean invokeLinked();

    void invokeUnlink();
}
