package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNode {

	long getKey();

	com.acuity.rs.api.RSNode getNext();

	com.acuity.rs.api.RSNode getPrevious();

	com.acuity.api.rs.wrappers.peers.structures.Node getWrapper();

	void setKey(long var0);

	void setNext(com.acuity.rs.api.RSNode var0);

	void setPrevious(com.acuity.rs.api.RSNode var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.structures.Node var0);
}
