package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNodeDeque {

    RSNode getCurrent();

    RSNode getHead();

    RSNode invokeCurrent();

    RSNode invokeNext();
}
