package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNormalFace {

	int getX();

	int getY();

	int getZ();

	void setX(int var0);

	void setY(int var0);

	void setZ(int var0);
}
