package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNodeQueue {

	com.acuity.rs.api.RSCacheableNode getRoot();

	void setRoot(com.acuity.rs.api.RSCacheableNode var0);
}
