package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSNodeDeque {

    RSNode getCurrent();

    RSNode getHead();

    com.acuity.rs.api.RSNode invokeCurrent();

    com.acuity.rs.api.RSNode invokeNext();
}
