package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNodeDeque {

	com.acuity.rs.api.RSNode getCurrent();

	com.acuity.rs.api.RSNode getHead();

	com.acuity.rs.api.RSNode invokeCurrent();

	com.acuity.rs.api.RSNode invokeNext();

	void setCurrent(com.acuity.rs.api.RSNode var0);

	void setHead(com.acuity.rs.api.RSNode var0);
}
