package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSActor
public interface RSNpc extends RSActor {

	com.acuity.rs.api.RSNPCType getType();

	com.acuity.api.rs.wrappers.peers.scene.actors.impl.Npc getWrapper();

	void setType(com.acuity.rs.api.RSNPCType var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.actors.impl.Npc var0);
}
