package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends: RSCacheableNode
public interface RSNPCComposite extends RSCacheableNode {

    String[] getActions();

    int getCombatLevel();

    int getId();

    int[] getModels();

    String getName();

    int[] getTransformIds();

    int getVarpbitIndex();

    int getVarpIndex();

    boolean isClickable();

    boolean isMinimapVisible();

    boolean isVisible();
}
