package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSActor
public interface RSNpc extends RSActor {

	com.acuity.rs.api.RSNPCComposite getDefinition();

	com.acuity.api.rs.wrappers.peers.scene.actors.impl.Npc getWrapper();

	void setDefinition(com.acuity.rs.api.RSNPCComposite var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.actors.impl.Npc var0);
}
