package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSNPCComposite extends RSCacheableNode {

	java.lang.String[] getActions();

	int getCombatLevel();

	int getHeadIcon();

	int[] getHeadIcons();

	int getId();

	int[] getModels();

	short[] getModifiedColors();

	java.lang.String getName();

	short[] getOriginalColors();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int[] getTransformIds();

	int getVarpbitIndex();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.composite.NpcComposite getWrapper();

	boolean isClickable();

	boolean isMinimapVisible();

	boolean isVisible();

	boolean isVisible1();

	void setActions(java.lang.String[] var0);

	void setClickable(boolean var0);

	void setCombatLevel(int var0);

	void setHeadIcon(int var0);

	void setHeadIcons(int[] var0);

	void setId(int var0);

	void setIsVisible1(boolean var0);

	void setMinimapVisible(boolean var0);

	void setModels(int[] var0);

	void setModifiedColors(short[] var0);

	void setName(java.lang.String var0);

	void setOriginalColors(short[] var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setTransformIds(int[] var0);

	void setVarpbitIndex(int var0);

	void setVarpIndex(int var0);

	void setVisible(boolean var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.NpcComposite var0);
}
