package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.mobiles.Npc;

//Generated by the injector on run.

//Extends RSActor
public interface RSNpc {

    RSNPCComposite getDefinition();

    Npc getWrapper();
}
