package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSNPCComposite extends RSCacheableNode {

	java.lang.String[] getActions();

	int getID();

	java.lang.String getName();

	short[] getNewColors();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	short[] getTextures();

	int[] getTransformIDs();

	int getVarpbitIndex();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.composite.NpcComposite getWrapper();

	void setActions(java.lang.String[] var0);

	void setID(int var0);

	void setName(java.lang.String var0);

	void setNewColors(short[] var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setTextures(short[] var0);

	void setTransformIDs(int[] var0);

	void setVarpbitIndex(int var0);

	void setVarpIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.NpcComposite var0);
}
