package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.mobiles.Npc;

//Generated by the injector on run.

//Extends: RSActor
public interface RSNpc extends RSActor {

    RSNPCComposite getDefinition();

    Npc getWrapper();
}
