package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSObjectNode extends RSNode {

	java.lang.Object getValue();

	void setValue(java.lang.Object var0);
}
