package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSOverlay extends RSCacheableNode {

	int getColor();

	int getHue();

	int getLightness();

	int getSaturation();

	int getTexture();

	boolean isHidden();

	void setColor(int var0);

	void setHidden(boolean var0);

	void setHue(int var0);

	void setLightness(int var0);

	void setSaturation(int var0);

	void setTexture(int var0);
}
