package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: RSCacheableNode
public interface RSOverlay extends RSCacheableNode {

    int getColor();

    int getHue();

    int getLightness();

    int getSaturation();

    int getTexture();

    boolean isHidden();
}
