package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSPendingSpawn extends RSNode {

	int getDelay();

	int getHitpoints();

	int getID();

	int getOrientation();

	int getPlane();

	int getSceneX();

	int getSceneY();

	int getType();

	void setDelay(int var0);

	void setHitpoints(int var0);

	void setID(int var0);

	void setOrientation(int var0);

	void setPlane(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setType(int var0);
}
