package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: RSNode
public interface RSPendingSpawn extends RSNode {

    int getDelay();

    int getHitpoints();

    int getId();

    int getLevel();

    int getOrientation();

    int getSceneX();

    int getSceneY();

    int getType();
}
