package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSPickableDecor {

	com.acuity.rs.api.RSRenderable getBottom();

	int getConfig();

	int getFineX();

	int getFineY();

	int getHash();

	int getHeight();

	com.acuity.rs.api.RSRenderable getMiddle();

	com.acuity.rs.api.RSRenderable getTop();

	void setBottom(com.acuity.rs.api.RSRenderable var0);

	void setConfig(int var0);

	void setFineX(int var0);

	void setFineY(int var0);

	void setHash(int var0);

	void setHeight(int var0);

	void setMiddle(com.acuity.rs.api.RSRenderable var0);

	void setTop(com.acuity.rs.api.RSRenderable var0);
}
