package com.acuity.rs.api;

import java.lang.String;
import com.acuity.api.rs.wrappers.peers.scene.actors.impl.Player;

//Generated by the injector on run.

//Extends: RSActor
public interface RSPlayer extends RSActor {

    String[] getActions();

    RSPlayerComposite getAppearance();

    int getCombatLevel();

    RSModel getModel();

    String getName();

    int getPrayerIcon();

    int getSkullIcon();

    int getTeam();

    int getTotalLevel();

    Player getWrapper();
}
