package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSPlayerComposite {

	int[] getBodyColors();

	int[] getEquipmentIDs();

	long getModelID();

	int getTransformedNpcID();

	com.acuity.api.rs.wrappers.peers.composite.PlayerComposite getWrapper();

	boolean isFemale();

	void setBodyColors(int[] var0);

	void setEquipmentIDs(int[] var0);

	void setFemale(boolean var0);

	void setModelID(long var0);

	void setTransformedNpcID(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.PlayerComposite var0);
}
