package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.peers.composite.PlayerComposite;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSPlayerComposite {

    int[] getBodyPartColors();

    int[] getEquipmentIds();

    long getHash();

    int getTransformedNpcId();

    PlayerComposite getWrapper();

    com.acuity.rs.api.RSModel invokeGetModel(RSAnimationSequence var0, int var1, RSAnimationSequence var2, int var3);

    boolean isFemale();
}
