package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSPreferences {

	java.util.LinkedHashMap getPreferences();

	int getResizable();

	boolean isLoginScreenAudioDisabled();

	boolean isRoofsHidden();

	void setLoginScreenAudioDisabled(boolean var0);

	void setPreferences(java.util.LinkedHashMap var0);

	void setResizable(int var0);

	void setRoofsHidden(boolean var0);
}
