package com.acuity.rs.api;


//Generated by the injector on run.

//Extends RSRenderable
public interface RSProjectile {

    RSAnimationSequence getAnimationSequence();

    double getCurrentY();

    int getCycle();

    int getFloor();

    int getHeight();

    double getHeightOffset();

    int getId();

    int getInteracting();

    int getSlope();

    double getSpeedY();

    int getStartTime();

    int getStrictX();

    int getStrictY();

    int getTargetDistance();

    double getVelocityX();

    double getVelocityY();

    double getVelocityZ();

    int getXRotation();

    int getYRotation();

    double getZ();

    boolean isMoving();
}
