package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.rendering.Renderable;

//Generated by the injector on run.

//Extends RSCacheableNode
public interface RSRenderable {

    int getHeight();

    Renderable getWrapper();

    RSModel invokeGetModel();
}
