package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSRenderOverview {

	void invokeExtractData(int var0, int var1, int var2, int var3, byte var4);

	void invokeExtractWorldmap(int var0, int var1, int var2, int var3, int var4, int var5);
}
