package com.acuity.rs.api;


//Generated by the injector on run.

//Abstract
//Extends java/lang/Object
public interface RSReferenceTable {

	java.lang.Object[][] getBuffer();

	com.acuity.rs.api.RSIdentityTable[] getChildren();

	com.acuity.rs.api.RSIdentityTable getEntry();

	byte[] invokeUnpack(int var0, int var1, int[] var2);

	void setBuffer(java.lang.Object[][] var0);

	void setChildren(com.acuity.rs.api.RSIdentityTable[] var0);

	void setEntry(com.acuity.rs.api.RSIdentityTable var0);
}
