package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSRenderable extends RSCacheableNode {

	com.acuity.rs.api.RSAxisAlignedBoundingBox getBoundingBox();

	com.acuity.api.rs.wrappers.peers.rendering.Model getCachedModel();

	int getHeight();

	com.acuity.api.rs.wrappers.peers.rendering.Renderable getWrapper();

	com.acuity.rs.api.RSModel invokeGetModel();

	void setBoundingBox(com.acuity.rs.api.RSAxisAlignedBoundingBox var0);

	void setCachedModel(com.acuity.api.rs.wrappers.peers.rendering.Model var0);

	void setHeight(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.rendering.Renderable var0);
}
