package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSScriptState {

    int getInvokedFromPc();

    RSScript getInvokedFromScript();

    int[] getSavedLocalInts();

    String[] getSavedLocalStrings();
}
