package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.elements.SceneTileDecor;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneTileDecor {

    RSRenderable getEntity();

    int getLevel();

    int getRenderInfoBitPacked();

    int getSceneX();

    int getSceneY();

    int getUid();

    SceneTileDecor getWrapper();
}
