package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSceneTileDecor {

	com.acuity.rs.api.RSRenderable getEntity();

	int getPlane();

	int getRenderInfoBitPacked();

	int getSceneX();

	int getSceneY();

	int getUid();

	com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneTileDecor getWrapper();

	void setEntity(com.acuity.rs.api.RSRenderable var0);

	void setPlane(int var0);

	void setRenderInfoBitPacked(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setUid(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneTileDecor var0);
}
