package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneTileModel {

    int getOverlay();

    int getRotation();

    int getShape();

    int getUnderlay();

    boolean isFlatShade();
}
