package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundaryDecor;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneBoundaryDecor {

    RSRenderable getEntity();

    int getOffsetX();

    int getOffsetY();

    int getOrientation();

    int getPlane();

    RSRenderable getRenderable2();

    int getRenderFlag();

    int getRenderInfoBitPacked();

    int getSceneX();

    int getSceneY();

    int getUID();

    SceneBoundaryDecor getWrapper();
}
