package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSceneBoundary {

	com.acuity.rs.api.RSRenderable getEntity();

	int getPlane();

	com.acuity.rs.api.RSRenderable getRenderable2();

	int getSceneX();

	int getSceneY();

	int getUid();

	com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundary getWrapper();

	void setEntity(com.acuity.rs.api.RSRenderable var0);

	void setPlane(int var0);

	void setRenderable2(com.acuity.rs.api.RSRenderable var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setUid(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundary var0);
}
