package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSceneElementComposite extends RSCacheableNode {

	java.lang.String[] getActions();

	int getAmbient();

	int getAnimationID();

	int getClipType();

	short[] getColors();

	int getContrast();

	int getID();

	int getMapIconID();

	int getMapSceneID();

	int getModelSizeHeight();

	int getModelSizeX();

	int getModelSizeY();

	java.lang.String getName();

	short[] getNewColors();

	int[] getObjectModels();

	int[] getObjectTypes();

	int getOffsetHeight();

	int getOffsetX();

	int getOffsetY();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int getSizeX();

	int getSizeY();

	short[] getTextureToFind();

	short[] getTextureToReplace();

	int[] getTransformIDs();

	int getVarpbitIndex();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.composite.SceneElementComposite getWrapper();

	com.acuity.rs.api.RSSceneElementComposite invokeGetImpostor(int var0);

	void invokeLoadData(com.acuity.rs.api.RSBuffer var0, int var1, short var2);

	boolean isClipped();

	boolean isNonFlatShading();

	boolean isRotated();

	boolean isSolid();

	void setActions(java.lang.String[] var0);

	void setAmbient(int var0);

	void setAnimationID(int var0);

	void setClipped(boolean var0);

	void setClipType(int var0);

	void setColors(short[] var0);

	void setContrast(int var0);

	void setID(int var0);

	void setMapIconID(int var0);

	void setMapSceneID(int var0);

	void setModelSizeHeight(int var0);

	void setModelSizeX(int var0);

	void setModelSizeY(int var0);

	void setName(java.lang.String var0);

	void setNewColors(short[] var0);

	void setNonFlatShading(boolean var0);

	void setObjectModels(int[] var0);

	void setObjectTypes(int[] var0);

	void setOffsetHeight(int var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setRotated(boolean var0);

	void setSizeX(int var0);

	void setSizeY(int var0);

	void setSolid(boolean var0);

	void setTextureToFind(short[] var0);

	void setTextureToReplace(short[] var0);

	void setTransformIDs(int[] var0);

	void setVarpbitIndex(int var0);

	void setVarpIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.SceneElementComposite var0);
}
