package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSSceneTile extends RSNode {

	com.acuity.rs.api.RSSceneBoundary getBoundary();

	com.acuity.rs.api.RSSceneBoundaryDecor getBoundaryDecor();

	com.acuity.rs.api.RSSceneElement[] getElements();

	com.acuity.rs.api.RSItemLayer getItemLayer();

	com.acuity.rs.api.RSSceneTileModel getModel();

	com.acuity.rs.api.RSSceneTilePaint getPaint();

	int getPlane();

	int getSceneX();

	int getSceneY();

	com.acuity.rs.api.RSSceneTileDecor getTileDecor();

	com.acuity.api.rs.wrappers.peers.scene.SceneTile getWrapper();

	void setBoundary(com.acuity.rs.api.RSSceneBoundary var0);

	void setBoundaryDecor(com.acuity.rs.api.RSSceneBoundaryDecor var0);

	void setElements(com.acuity.rs.api.RSSceneElement[] var0);

	void setItemLayer(com.acuity.rs.api.RSItemLayer var0);

	void setModel(com.acuity.rs.api.RSSceneTileModel var0);

	void setPaint(com.acuity.rs.api.RSSceneTilePaint var0);

	void setPlane(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setTileDecor(com.acuity.rs.api.RSSceneTileDecor var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.SceneTile var0);
}
