package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSceneElementComposite extends RSCacheableNode {

	java.lang.String[] getActions();

	int getAmbient();

	int getAmbientSoundId();

	int getAnimationId();

	int getClipType();

	short[] getColors();

	int getContrast();

	int getId();

	int getMapIconId();

	int getMapSceneId();

	int getModelSizeHeight();

	int getModelSizeX();

	int getModelSizeY();

	java.lang.String getName();

	short[] getNewColors();

	int[] getObjectModels();

	int[] getObjectTypes();

	int getOffsetHeight();

	int getOffsetX();

	int getOffsetY();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int getSizeX();

	int getSizeY();

	short[] getTextureToFind();

	short[] getTextureToReplace();

	int[] getTransformIds();

	int getVarpId();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.composite.SceneElementComposite getWrapper();

	com.acuity.rs.api.RSSceneElementComposite invokeGetImpostor(int var0);

	void invokeLoadData(com.acuity.rs.api.RSBuffer var0, int var1, short var2);

	boolean isClipped();

	boolean isClipped1();

	boolean isNonFlatShading();

	boolean isRotated();

	boolean isSolid();

	void setActions(java.lang.String[] var0);

	void setAmbient(int var0);

	void setAmbientSoundId(int var0);

	void setAnimationId(int var0);

	void setClipped(boolean var0);

	void setClipped1(boolean var0);

	void setClipType(int var0);

	void setColors(short[] var0);

	void setContrast(int var0);

	void setId(int var0);

	void setMapIconId(int var0);

	void setMapSceneId(int var0);

	void setModelSizeHeight(int var0);

	void setModelSizeX(int var0);

	void setModelSizeY(int var0);

	void setName(java.lang.String var0);

	void setNewColors(short[] var0);

	void setNonFlatShading(boolean var0);

	void setObjectModels(int[] var0);

	void setObjectTypes(int[] var0);

	void setOffsetHeight(int var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setRotated(boolean var0);

	void setSizeX(int var0);

	void setSizeY(int var0);

	void setSolid(boolean var0);

	void setTextureToFind(short[] var0);

	void setTextureToReplace(short[] var0);

	void setTransformIds(int[] var0);

	void setVarpId(int var0);

	void setVarpIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.composite.SceneElementComposite var0);
}
