package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSScene {

	com.acuity.rs.api.RSSceneElement[] getElements();

	com.acuity.rs.api.RSSceneTile[][][] getTiles();

	com.acuity.api.rs.wrappers.peers.scene.Scene getWrapper();

	void invokeAddPickableDecor(int var0, int var1, int var2, int var3, com.acuity.rs.api.RSRenderable var4, int var5, com.acuity.rs.api.RSRenderable var6, com.acuity.rs.api.RSRenderable var7);

	void setElements(com.acuity.rs.api.RSSceneElement[] var0);

	void setTiles(com.acuity.rs.api.RSSceneTile[][][] var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.Scene var0);
}
