package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSCacheableNode
public interface RSSceneElementType extends RSCacheableNode {

	java.lang.String[] getActions();

	int getAmbient();

	int getAmbientSoundId();

	int getAnimation();

	int getClipType();

	short[] getColors();

	int getContrast();

	int getID();

	int getItemSupport();

	int getMapIconID();

	int getMapSceneId();

	java.lang.String getName();

	short[] getNewColors();

	short[] getNewTextures();

	com.acuity.rs.api.RS3CopiedNodeTable getProperties();

	int getScaleX();

	int getScaleY();

	int getScaleZ();

	int getSizeX();

	int getSizeY();

	short[] getTextures();

	int[] getTransformIDs();

	int getTranslateX();

	int getTranslateY();

	int getTranslateZ();

	int getVarpbitIndex();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.types.SceneElementType getWrapper();

	boolean isClipped();

	boolean isImpenetrable();

	boolean isProjectileClipped();

	boolean isRotated();

	boolean isSolid();

	void setActions(java.lang.String[] var0);

	void setAmbient(int var0);

	void setAmbientSoundId(int var0);

	void setAnimation(int var0);

	void setClipped(boolean var0);

	void setClipType(int var0);

	void setColors(short[] var0);

	void setContrast(int var0);

	void setID(int var0);

	void setImpenetrable(boolean var0);

	void setItemSupport(int var0);

	void setMapIconID(int var0);

	void setMapSceneId(int var0);

	void setName(java.lang.String var0);

	void setNewColors(short[] var0);

	void setNewTextures(short[] var0);

	void setProjectileClipped(boolean var0);

	void setProperties(com.acuity.rs.api.RS3CopiedNodeTable var0);

	void setRotated(boolean var0);

	void setScaleX(int var0);

	void setScaleY(int var0);

	void setScaleZ(int var0);

	void setSizeX(int var0);

	void setSizeY(int var0);

	void setSolid(boolean var0);

	void setTextures(short[] var0);

	void setTransformIDs(int[] var0);

	void setTranslateX(int var0);

	void setTranslateY(int var0);

	void setTranslateZ(int var0);

	void setVarpbitIndex(int var0);

	void setVarpIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.types.SceneElementType var0);
}
