package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.elements.impl.SceneElement;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneElement {

    int getEndSceneX();

    int getEndSceneY();

    RSRenderable getEntity();

    int getFlag();

    int getHeight();

    int getOffsetX();

    int getOffsetY();

    int getOrientation();

    int getPlane();

    int getSceneX();

    int getSceneY();

    int getUID();

    SceneElement getWrapper();
}
