package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSNode
public interface RSScriptEvent extends RSNode {

	java.lang.Object[] getArgs();

	void setArgs(java.lang.Object[] var0);
}
