package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSceneBoundaryDecor {

	com.acuity.rs.api.RSRenderable getEntity();

	int getOffsetX();

	int getOffsetY();

	int getOrientation();

	int getPlane();

	com.acuity.rs.api.RSRenderable getRenderable2();

	int getRenderFlag();

	int getRenderInfoBitPacked();

	int getSceneX();

	int getSceneY();

	int getUID();

	com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundaryDecor getWrapper();

	void setEntity(com.acuity.rs.api.RSRenderable var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setOrientation(int var0);

	void setPlane(int var0);

	void setRenderable2(com.acuity.rs.api.RSRenderable var0);

	void setRenderFlag(int var0);

	void setRenderInfoBitPacked(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setUID(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundaryDecor var0);
}
