package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSScriptState {

	int getInvokedFromPc();

	com.acuity.rs.api.RSScript getInvokedFromScript();

	int[] getSavedLocalInts();

	java.lang.String[] getSavedLocalStrings();

	void setInvokedFromPc(int var0);

	void setInvokedFromScript(com.acuity.rs.api.RSScript var0);

	void setSavedLocalInts(int[] var0);

	void setSavedLocalStrings(java.lang.String[] var0);
}
