package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

//Extends RSCacheableNode
public interface RSScript extends RSCacheableNode {

    int[] getInstructions();

    int[] getIntOperands();

    int getIntStackCount();

    int getLocalIntCount();

    int getLocalStringCount();

    String[] getStringOperands();

    int getStringStackCount();

    Object[] getSwitches();
}
