package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSSceneBoundaryDecor {

	com.acuity.rs.api.RSRenderable getEntity();

	com.acuity.rs.api.RSRenderable getLinkedEntity();

	int getOffsetX();

	int getOffsetY();

	int getOrientation();

	int getPlane();

	int getSceneX();

	int getSceneY();

	int getUID();

	com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundaryDecor getWrapper();

	void setEntity(com.acuity.rs.api.RSRenderable var0);

	void setLinkedEntity(com.acuity.rs.api.RSRenderable var0);

	void setOffsetX(int var0);

	void setOffsetY(int var0);

	void setOrientation(int var0);

	void setPlane(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setUID(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.scene.elements.impl.SceneBoundaryDecor var0);
}
