package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneTilePaint {

    int getRgb();

    int getTexture();

    boolean isFlatShade();
}
