package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSSceneTileModel {

	int getOverlay();

	int getRotation();

	int getShape();

	int getUnderlay();

	boolean isFlatShade();

	void setFlatShade(boolean var0);

	void setOverlay(int var0);

	void setRotation(int var0);

	void setShape(int var0);

	void setUnderlay(int var0);
}
