package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSSceneOffset {

	int getLevel();

	int getX();

	int getY();

	void setLevel(int var0);

	void setX(int var0);

	void setY(int var0);
}
