package com.acuity.rs.api;

import com.acuity.api.rs.wrappers.scene.elements.SceneBoundary;

//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSSceneBoundary {

    RSRenderable getEntity();

    int getLevel();

    RSRenderable getRenderable2();

    int getSceneX();

    int getSceneY();

    int getUid();

    SceneBoundary getWrapper();
}
