package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSocket extends java.lang.Runnable {

	java.io.InputStream getInputStream();

	byte[] getOutbuffer();

	int getOutbufLen();

	java.io.OutputStream getOutputStream();

	java.net.Socket getSocket();

	void setInputStream(java.io.InputStream var0);

	void setOutbuffer(byte[] var0);

	void setOutbufLen(int var0);

	void setOutputStream(java.io.OutputStream var0);

	void setSocket(java.net.Socket var0);
}
