package com.acuity.rs.api;


//Generated by the injector on run.

//Extends RSRasterizer2D
public interface RSSpritePixels {

    int getHeight();

    int getMaxHeight();

    int getMaxWidth();

    int getOffsetX();

    int getOffsetY();

    int[] getPixels();

    int getWidth();
}
