package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSSpotAnimation extends RSCacheableNode {

	int getAmbience();

	int getAnimation();

	int getContrast();

	int getModelId();

	int getOrientation();

	int getScaleXY();

	int getScaleZ();

	void setAmbience(int var0);

	void setAnimation(int var0);

	void setContrast(int var0);

	void setModelId(int var0);

	void setOrientation(int var0);

	void setScaleXY(int var0);

	void setScaleZ(int var0);
}
