package com.acuity.rs.api;


//Generated by the injector on run.

//Extends jx
public interface RSSpotAnimationProvider {

	java.awt.Image getImage();

	void invokeDraw(java.awt.Graphics var0, int var1, int var2);

	void setImage(java.awt.Image var0);
}
