package com.acuity.rs.api;


//Generated by the injector on run.

//Extends com/acuity/rs/api/RSRenderable
public interface RSSpotAnimation extends RSRenderable {

	int getHeight();

	int getID();

	int getPlane();

	int getSceneX();

	int getSceneY();

	com.acuity.rs.api.RSAnimationSequence getSequence();

	boolean isFinished();

	void setFinished(boolean var0);

	void setHeight(int var0);

	void setID(int var0);

	void setPlane(int var0);

	void setSceneX(int var0);

	void setSceneY(int var0);

	void setSequence(com.acuity.rs.api.RSAnimationSequence var0);
}
