package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSTextureProviderImpl {

	com.acuity.rs.api.RSIndexDataBase getTable();

	void setTable(com.acuity.rs.api.RSIndexDataBase var0);
}
