package com.acuity.rs.api;


//Generated by the injector on run.

//Extends: java/lang/Object
public interface RSTextureProviderImpl extends RSTextureProvider {

    RSIndexDataBase getTable();

    int invokeLoad(int var0);
}
