package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSVarpbit extends RSCacheableNode {

	int getLeastSignificantBit();

	int getMostSignificantBit();

	int getVarpIndex();

	void setLeastSignificantBit(int var0);

	void setMostSignificantBit(int var0);

	void setVarpIndex(int var0);
}
