package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSVarpbit extends RSCacheableNode {

	int getLower();

	int getUpper();

	int getVarpIndex();

	com.acuity.api.rs.wrappers.peers.engine.Varpbit getWrapper();

	void setLower(int var0);

	void setUpper(int var0);

	void setVarpIndex(int var0);

	void setWrapper(com.acuity.api.rs.wrappers.peers.engine.Varpbit var0);
}
