package com.acuity.rs.api;


//Generated by the injector on run.

//Extends java/lang/Object
public interface RSWorld {

	java.lang.String getActivity();

	java.lang.String getDomain();

	int getID();

	int getIndex();

	int getLocation();

	int getMask();

	int getPopulation();

	void setActivity(java.lang.String var0);

	void setDomain(java.lang.String var0);

	void setID(int var0);

	void setIndex(int var0);

	void setLocation(int var0);

	void setMask(int var0);

	void setPopulation(int var0);
}
