package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSWorldMapData {

	int getFileID();

	void invokeLoadMapData(com.acuity.rs.api.RSBuffer var0, int var1, int var2);

	void setFileID(int var0);
}
