package com.acuity.rs.api;

import java.lang.String;

//Generated by the injector on run.

public interface RSWorld {

    String getActivity();

    String getDomain();

    int getID();

    int getIndex();

    int getLocation();

    int getMask();

    int getPopulation();
}
