package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSWorldMapData {

	java.lang.String getActivity();

	int getFileId();

	void invokeLoadMapData(com.acuity.rs.api.RSBuffer var0, int var1, int var2);

	void setActivity(java.lang.String var0);

	void setFileId(int var0);
}
