package com.acuity.rs.api;


//Generated by the injector on run.

public interface RSWorldMapData {

	java.lang.String getActivity();

	int getFileId();

	void setActivity(java.lang.String var0);

	void setFileId(int var0);
}
